language: cpp
compiler: g++
os: linux
dist: xenial
sudo: required

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install: 
    - sudo apt-get install -qq libjsoncpp-dev
    - sudo apt-get install -qq libboost-all-dev
    - sudo apt-get install -qq libgtest-dev
    - sudo apt-get install -qq g++-6 cmake
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
    # install gtest 
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -
    # Compile Zilch 
    - make -j8
    - make zilch-tests -j8
    - ./zilch-tests
